### PR TITLE
Prevent ANR and deprecate cause.

### PR DESCRIPTION
**Pull request by brandonpage**

### CODE REVIEW

**Review by JohnsonEricAtSalesforce — APPROVED** [review]
⭐️

**Comment by brandonpage** [comment]
The test failure is legitimate but unrelated to the changes in this PR.  I will fix that is a separate PR after merging this.

**Review by wmathurin — COMMENTED** [review]
Will 5s be enough? Should we provide a way for the app to choose the timeout value?

**Comment by brandonpage** [comment]
@wmathurin  [5 seconds is the longest timeout we can use to prevent ANR's](https://developer.android.com/topic/performance/vitals/anr#:~:text=An%20ANR%20is%20triggered%20for,onCreate()%20and%20Service).

**Pull request merged**
