### PR TITLE
Making SmartStore's backing DB access more stable

### PR DESCRIPTION
**Pull request by bhariharan**
This ensures every access to the DB goes through ```DBOpenHelper```, which ensures we always access a DB instance that hasn't been closed.

### CODE REVIEW

**Comment by bhariharan** [comment]
The original pull request came from the S1 team.

**Comment by wmathurin** [comment]
What if the db is closed after the call to dbOpenHelper.getWritableDatabase() and before it is used?

**Comment by bhariharan** [comment]
The helper is closed only on the ```deleteDb``` call, so that should never happen.

**Comment by khawkins** [comment]
Looks fine to me.

**Comment by wmathurin** [comment]
Is the helper returning a different db on every call?
Is there a performance impact getting a new db object every time?

**Comment by bhariharan** [comment]
No - the only thing that's different here is that the DB lifecycle is in sync with the lifecycle of ```DBOpenHelper```, which ensures that a stale, already closed DB object is never hanging around.

**Comment by wmathurin** [comment]
Makes sense.

**Comment by bhariharan** [comment]
Any other comments/concerns before I merge?

**Comment by wmathurin** [comment]
No, go ahead.

**Pull request merged**
