### PR TITLE
Fixing regressions

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by bhariharan** [comment]
Interesting! Is this a new requirement with ```OkHttp``` or always been there?

**Comment by bhariharan** [comment]
:+1:

**Comment by wmathurin** [comment]
The callback with okhttp is running on a network thread, so we have to be careful not to do any UI work.
A serious app should not do network calls directly from the UI code but our sample apps do ;-)

**Comment by bhariharan** [comment]
Sounds good. :+1:

**Comment by wmathurin** [comment]
Missed one, now fixed see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1090/commits/9dcbb2693e06198eae8ac1537f2b8174133458b3

**Comment by wmathurin** [comment]
Repro steps:
- create hybrid remote application
- login
- through a browser, login, go to setup, look for session, from the user session information page, remove all sessions
- reload hybrid remote application

Before the fix: it would crash
After the fix: it load the page (after doing a token / cookies refresh)

**Comment by bhariharan** [comment]
:+1:

**Pull request merged**
