### PR TITLE
Fixing API version accessors, so that they are truly overridable

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
I ran ```SmartSyncExplorer```, ```RestExplorer``` and ```SmartSyncExplorerHybrid```. Sample apps appear to be working fine. Running tests as we speak.

**Comment by wmathurin** [comment]
:+1:

**Comment by kchitalia** [comment]
:+1:

**Comment by bhariharan** [comment]
@aghoneim FYI - now you can override the string ```api_version``` in your app's ```strings.xml```, and specify the API version that you want to use. ```SmartSync``` will use that API version as well.

**Comment by ghonix** [comment]
:+1:

**Pull request merged**
