### PR TITLE
Removing Support for Eclipse and ant

### PR DESCRIPTION
**Pull request by bhariharan**
There's no going back.....

### CODE REVIEW

**Comment by bhariharan** [comment]
@wmathurin [This](https://github.com/forcedotcom/SalesforceMobileSDK-Android/commit/d2fa8ee02792845d9cddc02a4292757c04747f71) is the only useful commit. The other commit is just a mass remove operation. ```forcedroid.js``` updates to remove dependency on ```ant``` coming in another pull request.

**Comment by wmathurin** [comment]
Actually there is: http://git-scm.com/docs/git-revert ;-)

**Comment by bhariharan** [comment]
```git-revert``` is my safety net :-)

**Comment by wmathurin** [comment]
I didn't realize we still had the instructions for ant create_native

**Comment by wmathurin** [comment]
:+1:

**Comment by bhariharan** [comment]
That tells us how many people read those instructions in ```README.md``` ;-)

**Comment by kchitalia** [comment]
:+1:

**Pull request merged**
