### PR TITLE
Sample apps cleanup: readme updates + symlink updates 

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by bhariharan** [comment]
:+1:

**Comment by kchitalia** [comment]
:+1:

**Comment by bhariharan** [comment]
@wmathurin Should we remove the ```shared``` repo resources too, for the deleted sample apps?

**Comment by wmathurin** [comment]
We could.
There is a readme file in the shared repo explaining how do build an iOS/Android app from the samples.
Of course, because they are not in the main repo, there is a chance they regress without us noticing.
In any case, we need to keep UserList and VFConnector since they are used when creating hybrid local and hybrid remote apps with forceios/forcedroid.

**Comment by bhariharan** [comment]
We can leave them alone for now. Doesn't hurt.

**Pull request merged**
