### PR TITLE
Mobile SDK 4.1.1 Patch Release

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by kchitalia** [comment]
@bhariharan Just for my understanding, what did we change here? I don't see any code changes.

**Comment by bhariharan** [comment]
We've had a few bugfixes made on ```master``` in previous pull requests.

**Comment by kchitalia** [comment]
Cool. So just adding the 4.1.1 tag. Thanks.

**Comment by bhariharan** [comment]
No - there are bugfixes too.

**Comment by kchitalia** [comment]
Sorry, I meant bug fixes in previous pull requests and 4.1.1 tag in this one.

**Comment by bhariharan** [comment]
Yeah.

**Pull request merged**
