### PR TITLE
Helper script for releases

### PR DESCRIPTION
**Pull request by wmathurin**
```
Use this script to set Mobile SDK version number in source files
Usage: ./setversion.sh -v <versionName> -c <versionCode> [-d <isDev>]
  where: versionName is the version name e.g. 7.1.0
         versionCode is the version code e.g. 64
         isDev is yes or no (default) to indicate whether it is a dev build
```

Updates package.json, manifests, config.xml's and SalesforceSDKManager.java

### CODE REVIEW

**Comment by bhariharan** [comment]
@wmathurin The script needs to include updating the version number in `build.gradle` files as well. That's the version used while publishing the packages to `Maven` (at least, for now). I can send a PR later to consolidate version numbers in `Gradle` and pull them into the `Manifest` from `Gradle` programmatically.

**Comment by bhariharan** [comment]
One more file, @wmathurin - version number should be updated in `tools/generate_doc.sh`. It won't go from `7.0.0` to `7.1.0` though, it'll be going from `7.0` to `7.1`. It's of the format `x.y`.

**Comment by bhariharan** [comment]
And this file too -> `libs/test/SalesforceHybridTest/src/com/salesforce/androidsdk/phonegap/JavaScriptPluginVersionTest.java`. Check out [this doc](https://docs.google.com/document/d/1-nTmlYuvSOkr-m9yx0-CRNSH_RALf1Dm0D6TNunL2o0/edit#heading=h.7fe8qxl4rjvf) for the full list.

**Comment by wmathurin** [comment]
@bhariharan Issues addressed here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1840

**Pull request merged**
