### PR TITLE
fix SmartSyncExplorerReactNative logout issue

### PR DESCRIPTION
**Pull request by ivanbogdanov**

### CODE REVIEW

**Comment by ivanbogdanov** [comment]
@wmathurin

**Comment by wmathurin** [comment]
The problem probably resides in SalesforceReacActivity and / or with the app itself.

**Comment by bhariharan** [comment]
Agree with @wmathurin. One of the biggest differences in `React` app and `Cordova` app is that `SalesforceReactActivity` extends `ReactActivity` and not our `Activity`, whereas `SalesforceDroidGapActivity` is ours, so we setup the `getRestClient` properly. We need to ensure the `registerSoup` call happens only after `getRestClient` returns with a valid `RestClient`.

**Comment by ivanbogdanov** [comment]
I think it reveals larger problem: most bridge methods shouldn't be called if a user is not logged in.

**Comment by wmathurin** [comment]
The oauth bridge logout method calls logout on the SalesforceReactActivity which calls logout on SalesforceSDKManager which should finish the SalesforceReactActivity. After login, it should be re-created. Somehow the react code starts too soon. I'm pretty sure that was working correctly with older version of React native. I wonder if they keep the javascript context around.

**Comment by ivanbogdanov** [comment]
Developers can call these bridge methods outside of  SalesforceReactActivity just from ReactActivity right?

**Comment by wmathurin** [comment]
They need to use SalesforceReactActivity (just like cordova developers that use our SDK must use SalesforceDroidGapActivity).

**Comment by ivanbogdanov** [comment]
I have just double-checked: registerSoup is called first time BEFORE login.

**Comment by bhariharan** [comment]
@ivanbogdanov Looks like we need to fix that in the app, so that it gets called only AFTER login.

**Comment by ivanbogdanov** [comment]
Do we care about scenarios of app functionality without / before login?

**Comment by bhariharan** [comment]
App could do anything that doesn't require login before login. For example, global `SmartStore` would probably work.

**Comment by ivanbogdanov** [comment]
Is global `SmartStore` call allowed for an authenticated user?

**Comment by wmathurin** [comment]
There is no problem after first logging in. The problem only arise on
logout. I think the react context is live too soon (or was never tear down).

**Comment by bhariharan** [comment]
@ivanbogdanov Let's close this PR and discuss app level solutions offline.

**Pull request closed without merging**
