### PR TITLE
ingonre the build folder for all libs at the npm package

### PR DESCRIPTION
**Pull request by helenren**

### CODE REVIEW

**Comment by kchitalia** [comment]
Nice! 👍

**Comment by bhariharan** [comment]
@helenren Did it work? Did you verify?

**Comment by helenren** [comment]
Yes, @bhariharan I tried locally:

1. the created npm package does not include build anymore
2. using the new package, the reac_native app created can build and launch successfully

Is there any other test I need to run? Thanks

**Comment by bhariharan** [comment]
👍

**Pull request merged**
