### PR TITLE
Upgrading to okhttp 4

### PR DESCRIPTION
**Pull request by wmathurin**
Interestingly the package is still com.squareup.okhttp3 ;-)

### CODE REVIEW

**Comment by wmathurin** [comment]
Testing ongoing.

**Review by brandonpage — APPROVED** [review]
I was hoping it "just worked" with the existing `okhttp3` import 👍

**Comment by wmathurin** [comment]
Locally:
- all SalesforceSDK tests passing
- MobileSync tests have a couple of failures with the second one causing the VM to exit (testSyncUpWithLocallyUpdatedRemotelyDeletedRecords). If I revert okhttp back to 3.12.12, all the tests pass. 

I'll investigate further...

**Comment by wmathurin** [comment]
I was able to run all the tests for MobileSync with okthttp4 - not sure what happened earlier.

**Comment by wmathurin** [comment]
SalesforceHybrid tests all passing.

**Comment by wmathurin** [comment]
Sending the change in. Not seeing any red flag when running tests locally.

**Pull request merged**
