### PR TITLE
Upgrade to SQLCipher 3.5.2 for Android N Support

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by wmathurin** [comment]
3.5.2 came out a few days ago. Should we use that instead?

**Comment by bhariharan** [comment]
@wmathurin Yeah - makes sense. I'll bump it up and test with it.

**Comment by bhariharan** [comment]
I tested running ```SmartSyncExplorer``` with the new version of ```SQLCipher```. I also tested running the upgrade scenario. Everything seems to work great. I think we're good to go on merging.

**Comment by kchitalia** [comment]
Hybrid SmartSyncExplorer looks good too?

**Comment by bhariharan** [comment]
Yup, looks good to me.

**Pull request merged**
