### PR TITLE
@W-13668007: [Android][Modernization] Remove MSDK Android MobileSyncExplorer Sample App In Favor of MSDK Templates Kotlin Compose Version

### PR DESCRIPTION
**Pull request by JohnsonEricAtSalesforce**
🎸 _Ready For Review_ 🥁

  This removes the Java native MobileSyncExplorer sample app since it is outdated and the Kotlin MobileSyncExplorer template with Jetpack Compose can be used in its place for testing and new apps.

### CODE REVIEW

**Review by wmathurin — COMMENTED** [review]
README needs to be updated see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/native/README.md?plain=1#L22)

After this PR:

1. Our IDP template has a reference to this app: see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt#L52)
2. There are some references in the doc: see [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_sample_app.htm?q=mobilesyncexplorer) and in a few more places

**Comment by wmathurin** [comment]
[One more reference](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/tools/sdk.sh#L59) in this repo

**Comment by JohnsonEricAtSalesforce** [comment]
> README needs to be updated see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/native/README.md?plain=1#L22)
> 
> After this PR:
> 
> 1. Our IDP template has a reference to this app: see [here](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/blob/dev/AndroidIDPTemplate/app/src/com/salesforce/samples/salesforceandroididptemplateapp/MainApplication.kt#L52)
> 2. There are some references in the doc: see [here](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_sample_app.htm?q=mobilesyncexplorer) and in a few more places

For point #1 about the IDP Template App, would we want to update the MobileSyncExplorerKotlinTemplate to fill the same role? We'd either need to update the reference in the IDP Template App or the MobileSyncExplorerKotlinTemplate so they still matched package and activity names.

**Comment by JohnsonEricAtSalesforce** [comment]
By the by, I am also doing a side by side comparison of the two Mobile Sync Explorer apps to document feature differences and bugs.  If the new app needs any fixes or quick features to live up to the previous one, I'll have notes on those and inline them to this effort if they are trivial efforts.

**Comment by wmathurin** [comment]
> For point #1 about the IDP Template App, would we want to update the MobileSyncExplorerKotlinTemplate to fill the same role? We'd either need to update the reference in the IDP Template App or the MobileSyncExplorerKotlinTemplate so they still matched package and activity names.

Or we could just have RestExplorer in the list of apps (I don't think it's going to go away - it wouldn't be a very useful template).

**Comment by JohnsonEricAtSalesforce** [comment]
This now has a companion pull request in SalesforceMobileSDK-Templates 👉🏻 https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/384

**Comment by wmathurin** [comment]
> By the by, I am also doing a side by side comparison of the two Mobile Sync Explorer apps to document feature differences and bugs. If the new app needs any fixes or quick features to live up to the previous one, I'll have notes on those and inline them to this effort if they are trivial efforts.

**Comment by JohnsonEricAtSalesforce** [comment]
@wmathurin - I also am following up on the documentation updates.

**Review by wmathurin — APPROVED** [review]

**Comment by brandonpage** [comment]
Just a heads up, there is a reference to MobileSyncExplorer [here in the doc](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_native_deferred_login.htm?q=defer).

**Comment by JohnsonEricAtSalesforce** [comment]
> Just a heads up, there is a reference to MobileSyncExplorer [here in the doc](https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/android_native_deferred_login.htm?q=defer).

Great find.  I reviewed that and left Steven some detailed notes for his 12.0.0 documentation delights.

**Pull request merged**
