### PR TITLE
 Improved logic to recognize soup column in result set

### PR DESCRIPTION
**Pull request by wmathurin**
Also added test (which fails with old code)

### CODE REVIEW

**Comment by brandonpage** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/94a8cb02785938dc417e11db2f9c79b4c55294f8/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java#L1349">libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java#L1349</a> - Implicitly using the default locale is a common source of bugs: Use <code>String.format(Locale, ...)</code> instead</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | Classname | Time|
--- | --- | ---|
No tests found. | com.android.builder.testing.ConnectedDevice | 0.001|


# Tests results for SmartStore

<p align="right" data-meta="generated_by_SmartStore">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bhariharan** [comment]
@wmathurin Do we need this on `Android`? There's no `FMDB` on `Android`.

**Comment by wmathurin** [comment]
The column names in the result set cursor are unique on Android as well.
The new test I wrote fails before the fix (and works with it).

**Comment by bhariharan** [comment]
👍 

Looks like some `SmartStoreInspectorActivityTests` are failing.

**Comment by wmathurin** [comment]
@bhariharan startsWith was not good enough (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1605/commits/8071292481b97ef77cfdedeee8389100b6c7ff1d) 
Now all the tests are passing.

**Pull request merged**
