### PR TITLE
Adding native network plugin implementation

### PR DESCRIPTION
**Pull request by bhariharan**
Added a native `Cordova` plugin for networking.

### CODE REVIEW

**Comment by bhariharan** [comment]
I have `AccountEditor` working end to end with the new network stack.

**Comment by bhariharan** [comment]
`forcetk` tests are passing too.

**Comment by bhariharan** [comment]
Should be good to go now.

**Comment by bhariharan** [comment]
@wmathurin Good idea. Using response headers [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1249/commits/50fa2a62e889edb7e642c707fd0e209085396be4). That works.

**Comment by wmathurin** [comment]
Maybe the block of code that figures out if there is a response body belongs in RestResponse.java?

**Comment by bhariharan** [comment]
@wmathurin Done [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1249/commits/0e54282edad45ed35eabbe28a3b7a9fcd81487ec).

**Comment by wmathurin** [comment]
:+1:

**Pull request merged**
