### PR TITLE
Bug fix in regex

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
Fix for this [issue](https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1273).

**Comment by bhariharan** [comment]
We already have a test for `cleanResyncGhosts`. We need to add a custom object with a custom field with `from` in it to explicitly test this.

**Comment by wmathurin** [comment]
I see. Or if the soql transforming code was in its own helper method, we could test it in isolation of the rest. Anyway, it's up to you.

**Comment by bhariharan** [comment]
It's specific to the `SOQL` target right now. Extracting it out for this test might need a little work, so I'll leave it as is for now.

**Pull request merged**
