### PR TITLE
Tolerate the lack of existing Accounts on the device when app logs in for the first time

### PR DESCRIPTION
**Pull request by daveespo**
Fix for #862

### CODE REVIEW

**Comment by kchitalia** [comment]
One suggestion, can we have a check for null and length > 0?

**Comment by daveespo** [comment]
The Android SDK docs make it pretty clear that null is not a valid return value:

> @return An array of {@link Account}, one per matching account.  Empty (never null) if no accounts of the specified type have been added.

**Comment by kchitalia** [comment]
Sorry, my bad.

**Comment by bhariharan** [comment]
Thanks for the contribution @daveespo!

**Pull request merged**
