### PR TITLE
Alter soup with spec

### PR DESCRIPTION
**Pull request by wmathurin**
alterSoup native signature lined up with iOS / hybrid
running new hybrid tests (for register with spec and alter with spec)
latest shared

### CODE REVIEW

**Comment by wmathurin** [comment]
DO NOT MERGE YET
One of the new test is not passing on Android (but passes on iOS and a browser)

**Comment by bhariharan** [comment]
👍

**Comment by wmathurin** [comment]
Enhanced hybrid tests (for alter soup with spec) are passing thanks to https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/1218/commits/641552865eeaef777667a060a1e44ecd466813a7

**Comment by bhariharan** [comment]
👍

**Pull request merged**
