### PR TITLE
Switched logging to INFO for connected Android test tasks

### PR DESCRIPTION
**Pull request by clibc**
When the connected Android tests are running, there's no log output and Travis thinks that the build has hung after 10 minutes. This change makes the test task (and only the test task) print out both passed and failed tests. I think that having a 10 minute watchdog is a good idea and it's better to make the  test task more verbose.

Unfortunately due to the way the Android Gradle plugin works, I have to add a snippet of Groovy to each build file instead of being able to add it once in an `allprojects` block.

### CODE REVIEW

**Comment by clibc** [comment]
@kchitalia take a look at this too

**Comment by bhariharan** [comment]
@clibc Could you add this to ```RestExplorer```, ```TemplateApp``` and ```SmartSyncExplorer``` too? Those projects have associated tests too. Thanks!

**Comment by wmathurin** [comment]
:+1:

**Comment by kchitalia** [comment]
This is awesome. :100:

**Pull request merged**
