### PR TITLE
Updating sf__login.xml to no longer place webview in a scrollview and fit height

### PR DESCRIPTION
**Pull request by smcnulty-sfdc**
Current layout design causes blank space to appear in the view if the content doesn't fill the entire height.  

Change allows the webview to fill the entire height of the viewport and control it's own scroll instead of placing it inside of a scrollview.

### CODE REVIEW

**Comment by bhariharan** [comment]
@smcnulty-sfdc What happens to the `IDP button` below it, if it's enabled? If the login webview takes the parent's height, the IDP button will be always hidden.

**Comment by bhariharan** [comment]
@smcnulty-sfdc Revert your last commit back to `RelativeLayout`. It seems to work fine with your changes.

**Comment by bhariharan** [comment]
before

**Comment by smcnulty-sfdc** [comment]
@bhariharan adjusted layout to be linear, gave the webview a weight so it will auto-adjust size to fit and give space for the button when it is visible.

**Pull request merged**
